// Houseplant care profiles: sources and scope in SOURCES.md.
const plants = [
  {
    id: "aloe", name: {"en": "Aloe vera", "fr": "Aloe vera"},
    genderFr: "m",
    botanical: "Aloe vera", water: "dry", light: {"ideal": ["sun", "partial"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Let the growing medium dry completely between waterings; use very well-drained succulent mix.", "fr": "Laisse le substrat sécher complètement entre deux arrosages ; utilise un mélange pour succulentes très drainant."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aloe-vera/",
  },
  {
    id: "spider", name: {"en": "Spider plant", "fr": "Plante araignée"},
    genderFr: "f", aliases: ["Chlorophytum", "Spider ivy", "Ribbon plant"],
    botanical: "Chlorophytum comosum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the soil moist and avoid direct sun. Reduce watering in winter.", "fr": "Garde le substrat humide et évite le soleil direct. Réduis les arrosages en hiver."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chlorophytum-comosum/",
  },
  {
    id: "peace", name: {"en": "Peace lily", "fr": "Fleur de lune"},
    genderFr: "f", aliases: ["Peace plant", "Lys de la paix", "Spathiphyllum"],
    botanical: "Spathiphyllum", water: "moist", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the medium moist, not soggy, and avoid direct sun and cold drafts.", "fr": "Garde le substrat humide, sans le détremper, et évite le soleil direct et les courants d’air froid."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/spathiphyllum/",
  },
  {
    id: "snake", name: {"en": "Snake plant", "fr": "Langue de belle-mère"},
    genderFr: "f", aliases: ["Sansevieria", "Sansevieria trifasciata", "Mother-in-law’s tongue", "Langue de belle mère"],
    botanical: "Dracaena trifasciata", water: "dry", light: {"ideal": ["partial"], "tolerated": ["indirect", "low"], "avoid": []},
    note: {"en": "Let the soil dry between waterings. It tolerates low light and some direct sun, but overwatering can rot its roots.", "fr": "Laisse sécher le substrat entre deux arrosages. Elle tolère peu de lumière et un peu de soleil direct, mais l’excès d’eau peut faire pourrir ses racines."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/",
  },
  {
    id: "pothos", name: {"en": "Pothos", "fr": "Pothos"},
    genderFr: "m", aliases: ["Scindapsus aureus", "Golden pothos", "Devil’s ivy", "Lierre du diable"],
    botanical: "Epipremnum aureum", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["sun"]},
    note: {"en": "Let the well-drained medium dry between waterings. Low light is tolerated but may reduce leaf variegation.", "fr": "Laisse sécher le substrat bien drainant entre deux arrosages. Une faible lumière est tolérée, mais peut atténuer les panachures."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/epipremnum-aureum/",
  },
  {
    id: "fiddle", name: {"en": "Fiddle-leaf fig", "fr": "Figuier lyre"},
    genderFr: "m",
    botanical: "Ficus lyrata", water: "moist", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the medium moist but well drained; protect from afternoon sun and avoid overwatering.", "fr": "Garde le substrat humide mais bien drainé ; protège du soleil de l’après-midi et évite l’excès d’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-lyrata/",
  },
  {
    id: "rubber", name: {"en": "Rubber plant", "fr": "Caoutchouc"},
    genderFr: "m",
    botanical: "Ficus elastica", water: "dry", light: {"ideal": ["indirect", "low"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Avoid overwatering and afternoon sun. Reduce watering during the dormant season.", "fr": "Évite l’excès d’eau et le soleil de l’après-midi. Réduis les arrosages pendant la période de repos."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-elastica/",
  },
  {
    id: "dracaena", name: {"en": "Corn plant", "fr": "Dragonnier parfumé"},
    genderFr: "m",
    botanical: "Dracaena fragrans", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the soil moist during growth and water less in winter. Direct sun can burn the leaves.", "fr": "Garde le substrat humide en période de croissance et arrose moins en hiver. Le soleil direct peut brûler les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-fragrans/",
  },
  {
    id: "zz", name: {"en": "ZZ plant", "fr": "Plante ZZ"},
    genderFr: "f", aliases: ["Zamioculcas", "Zanzibar gem"],
    botanical: "Zamioculcas zamiifolia", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Let the soil dry completely before watering. Direct sun can scorch its leaves.", "fr": "Laisse sécher le substrat complètement avant d’arroser. Le soleil direct peut brûler ses feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/zamioculcas-zamiifolia/",
  },
  {
    id: "fern", name: {"en": "Boston fern", "fr": "Fougère de Boston"},
    genderFr: "f", aliases: ["Fougère de Boston", "Sword fern"],
    botanical: "Nephrolepis exaltata", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Do not let the medium dry out. This fern needs high humidity; reduce watering during winter dormancy.", "fr": "Ne laisse pas sécher le substrat. Cette fougère apprécie une forte humidité ambiante ; réduis les arrosages pendant le repos hivernal."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/nephrolepis-exaltata/",
    waterAvoid: ["dry"],
  },
  {
    id: "jade", name: {"en": "Jade plant", "fr": "Arbre de jade"},
    genderFr: "m", aliases: ["Crassula", "Money plant"],
    botanical: "Crassula ovata", water: "dry", light: {"ideal": ["partial"], "tolerated": ["indirect"], "avoid": ["low", "sun"]},
    note: {"en": "Water when the soil is dry and reduce watering from autumn to late winter. Provide a sunny spot with afternoon protection.", "fr": "Arrose quand le substrat est sec et réduis les arrosages de l’automne à la fin de l’hiver. Choisis un emplacement ensoleillé, protégé l’après-midi."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/crassula-ovata/",
  },
  {
    id: "violet", name: {"en": "African violet", "fr": "Violette africaine"},
    genderFr: "f", aliases: ["Saintpaulia", "Saintpaulia ionantha"],
    botanical: "Streptocarpus ionanthus", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the surface dry before watering again. Bottom watering keeps water off the leaves.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Un arrosage par le bas évite de mouiller les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/streptocarpus-ionanthus/",
  },
  {
    id: "orchid", name: {"en": "Orchid", "fr": "Orchidée"},
    genderFr: "f", aliases: ["Moth orchid", "Orchidée papillon"],
    botanical: "Phalaenopsis", water: "surface", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Use a bark-based orchid medium, let it dry somewhat between waterings and drain the pot fully.", "fr": "Utilise un substrat pour orchidées à base d’écorces, laisse-le sécher partiellement entre deux arrosages et égouttez complètement le pot."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/phalaenopsis/",
  },
  {
    id: "calathea", name: {"en": "Calathea", "fr": "Calathéa"},
    genderFr: "m", aliases: ["Calathea", "Goeppertia"],
    botanical: "Goeppertia", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the medium moist, not soggy. Avoid direct sun, cold drafts and sudden temperature changes.", "fr": "Garde le substrat humide, sans le détremper. Évite le soleil direct, les courants d’air froid et les changements brusques de température."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/goeppertia/",
  },
  {
    id: "philodendron", name: {"en": "Heartleaf philodendron", "fr": "Philodendron"},
    genderFr: "m", aliases: ["Philodendron scandens", "Philodendron cordatum", "Sweetheart plant"],
    botanical: "Philodendron hederaceum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the soil slightly moist and water less in winter. Low light is tolerated.", "fr": "Garde le substrat légèrement humide et arrose moins en hiver. Une faible lumière est tolérée."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/philodendron-hederaceum/",
  },
  {
    id: "monstera", name: {"en": "Monstera", "fr": "Monstera"},
    genderFr: "f", aliases: ["Swiss cheese plant", "Split-leaf philodendron", "Faux philodendron"],
    botanical: "Monstera deliciosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Let the upper part of the medium dry between thorough waterings. Avoid direct sun.", "fr": "Laisse sécher la partie supérieure du substrat entre deux arrosages complets. Évite le soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/monstera-deliciosa/",
  },
  {
    id: "bromeliad", name: {"en": "Guzmania", "fr": "Guzmania"},
    genderFr: "m",
    botanical: "Guzmania lingulata", water: "tank", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep water in the rosette’s central cup, especially in summer; water the roots sparingly in bromeliad or orchid mix.", "fr": "Garde de l’eau dans la coupe centrale de la rosette, surtout en été ; arrose peu les racines dans un substrat pour broméliacées ou orchidées."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/guzmania-lingulata/",
  },
  {
    id: "cactus", name: {"en": "Cactus", "fr": "Cactus"},
    genderFr: "m", aliases: ["Cactus désertique", "Desert cactus", "Pincushion cactus"],
    botanical: "Mammillaria", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Let the soil dry completely between waterings. Suspend watering during winter dormancy.", "fr": "Laisse sécher le substrat complètement entre deux arrosages. Suspends les arrosages pendant le repos hivernal."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/mammillaria/",
  },
  {
    id: "echeveria", name: {"en": "Echeveria", "fr": "Échévéria"},
    genderFr: "f",
    botanical: "Echeveria", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Provide a sunny spot; this desert succulent needs little water.", "fr": "Offre un emplacement ensoleillé ; cette succulente désertique a besoin de peu d’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/echeveria/",
  },
  {
    id: "hoya", name: {"en": "Wax plant", "fr": "Fleur de porcelaine"},
    genderFr: "f", aliases: ["Hoya", "Wax flower"],
    botanical: "Hoya carnosa", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Let the soil dry between waterings. Both overly wet and overly dry soil can cause leaf drop.", "fr": "Laisse sécher le substrat entre deux arrosages. Un substrat trop humide ou trop sec peut faire tomber les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/hoya-carnosa/",
  },
  {
    id: "kalanchoe", name: {"en": "Kalanchoe", "fr": "Kalanchoé"},
    genderFr: "m",
    botanical: "Kalanchoe blossfeldiana", water: "dry", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the soil dry between waterings, then water thoroughly. Prolonged direct sun can scorch the leaves.", "fr": "Laisse sécher le substrat entre deux arrosages, puis arrose abondamment. Un soleil direct prolongé peut brûler les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/kalanchoe-blossfeldiana/",
  },
  {
    id: "pilea", name: {"en": "Chinese money plant", "fr": "Pilea"},
    genderFr: "m", aliases: ["Plante à monnaie chinoise", "Pancake plant", "Missionary plant"],
    botanical: "Pilea peperomioides", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Use moist, well-drained medium and bright indirect light. Overwatering can cause root rot.", "fr": "Utilise un substrat humide, bien drainé et une lumière vive indirecte. L’excès d’eau peut faire pourrir les racines."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/pilea-peperomioides/",
  },
  {
    id: "peperomia", name: {"en": "Peperomia", "fr": "Pépéromia"},
    genderFr: "m",
    botanical: "Peperomia obtusifolia", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Avoid wet soil, extreme dryness and direct sun. Bright indirect light is preferred.", "fr": "Évite un substrat détrempé, une sécheresse excessive et le soleil direct. Une lumière vive indirecte est préférable."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/peperomia-obtusifolia/",
  },
  {
    id: "schefflera", name: {"en": "Dwarf umbrella tree", "fr": "Arbre ombrelle"},
    genderFr: "m", aliases: ["Schefflera arboricola", "Dwarf schefflera", "Parasol"],
    botanical: "Heptapleurum arboricola", water: "dry", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the soil dry, then water thoroughly. Direct sun can burn the leaves indoors.", "fr": "Laisse sécher le substrat, puis arrose abondamment. À l’intérieur, le soleil direct peut brûler les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/heptapleurum-arboricola/",
  },
  {
    id: "ficus", name: {"en": "Weeping fig", "fr": "Figuier pleureur"},
    genderFr: "m", aliases: ["Ficus benjamina"],
    botanical: "Ficus benjamina", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial", "low"], "avoid": ["sun"]},
    note: {"en": "Water before the soil dries completely. Moving the plant to different light can cause leaf drop.", "fr": "Arrose avant que le substrat ne sèche complètement. Un changement d’exposition peut faire tomber les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-benjamina/",
    waterAvoid: ["dry"],
  },
  {
    id: "anthurium", name: {"en": "Anthurium", "fr": "Anthurium"},
    genderFr: "m",
    botanical: "Anthurium andraeanum", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Water when the top of the soil feels dry. Avoid direct sun and cold drafts.", "fr": "Arrose quand la surface du substrat est sèche au toucher. Évite le soleil direct et les courants d’air froid."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/anthurium-andraeanum/",
  },
  {
    id: "rex", name: {"en": "Rex begonia", "fr": "Bégonia rex"},
    genderFr: "m", aliases: ["Begonia rex"],
    botanical: "Begonia Rex Cultorum Group", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the medium moist and well drained. Avoid misting and overwatering.", "fr": "Garde le substrat humide et bien drainé. Évite la brumisation et l’excès d’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/begonia-rex-types/",
  },
  {
    id: "maranta", name: {"en": "Prayer plant", "fr": "Maranta"},
    genderFr: "m",
    botanical: "Maranta leuconeura", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the soil evenly moist during growth; reduce watering in winter. Avoid direct sun.", "fr": "Garde le substrat uniformément humide en période de croissance ; réduis les arrosages en hiver. Évite le soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/maranta-leuconeura/",
  },
  {
    id: "marginata", name: {"en": "Dragon tree", "fr": "Dragonnier de Madagascar"},
    genderFr: "m", aliases: ["Dracaena reflexa var. angustifolia"],
    botanical: "Dracaena marginata", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the medium dry between waterings, but not severely. Bright indirect light is ideal.", "fr": "Laisse sécher le substrat entre deux arrosages, sans sécheresse excessive. Une lumière vive indirecte est idéale."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-reflexa-var-angustifolia/",
  },
  {
    id: "cyclamen", name: {"en": "Florist’s cyclamen", "fr": "Cyclamen des fleuristes"},
    genderFr: "m",
    botanical: "Cyclamen persicum", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Water when the soil feels dry, avoiding the crown. Keep it cool and reduce watering during summer dormancy.", "fr": "Arrose quand le substrat est sec au toucher, sans mouiller le cœur. Garde la plante au frais et réduis les arrosages pendant le repos estival."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/cyclamen-persicum/",
  },
  {
    id: "aglaonema", name: {"en": "Chinese evergreen", "fr": "Aglaonema"},
    genderFr: "m",
    botanical: "Aglaonema", water: "moist", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the mix lightly moist during growth and water less in winter. Avoid cold drafts.", "fr": "Garde le terreau légèrement humide en période de croissance et arrose moins en hiver. Évite les courants d’air froid."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aglaonema/",
  },
  {
    id: "alocasia", name: {"en": "Alocasia", "fr": "Alocasia"},
    genderFr: "f", aliases: ["Alocasia amazonica", "Alocasia × amazonica", "Alocasia mortfontanensis", "African mask plant"],
    botanical: "Alocasia × mortfontanensis", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the mix moist but well drained. Direct sun can scorch the leaves; reduce watering when growth slows.", "fr": "Garde le terreau humide mais bien drainé. Le soleil direct peut brûler les feuilles ; arrose moins quand la croissance ralentit."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/alocasia-x-mortfontanensis/",
  },
  {
    id: "aspidistra", name: {"en": "Cast iron plant", "fr": "Aspidistra"},
    genderFr: "f", aliases: ["Plante de fer"],
    botanical: "Aspidistra elatior", water: "surface", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "It tolerates shade and dry spells. Water regularly during growth, less in winter, and avoid direct sun.", "fr": "Elle tolère l’ombre et les périodes sèches. Arrose régulièrement en période de croissance, moins en hiver, et évite le soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aspidistra-elatior/",
  },
  {
    id: "dieffenbachia", name: {"en": "Dieffenbachia", "fr": "Dieffenbachia"},
    genderFr: "m",
    botanical: "Dieffenbachia seguine", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Let the surface dry before watering again. Keep it away from direct sun and cold drafts.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Évite le soleil direct et les courants d’air froid."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dieffenbachia-seguine/",
  },
  {
    id: "syngonium", name: {"en": "Arrowhead plant", "fr": "Syngonium"},
    genderFr: "m", aliases: ["Nephthytis"],
    botanical: "Syngonium podophyllum", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the mix moist. Avoid strong direct sun, which can burn or bleach the leaves.", "fr": "Garde le terreau humide. Évite le soleil direct intense, qui peut brûler ou décolorer les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/syngonium-podophyllum/",
  },
  {
    id: "fittonia", name: {"en": "Nerve plant", "fr": "Fittonia"},
    genderFr: "m",
    botanical: "Fittonia albivenis", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Do not let it dry out: it wilts dramatically when thirsty. Avoid direct sun and do not leave the roots waterlogged.", "fr": "Ne le laisse pas sécher : il s’affaisse vite quand il a soif. Évite le soleil direct et ne laisse pas les racines baigner dans l’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/fittonia-albivenis/",
  },
  {
    id: "croton", name: {"en": "Croton", "fr": "Croton"},
    genderFr: "m", aliases: ["Codiaeum"],
    botanical: "Codiaeum variegatum", water: "surface", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Give it bright light with some sun for good leaf colour. Water less in winter and avoid a permanently wet pot.", "fr": "Offre-lui une lumière vive avec du soleil pour de belles couleurs. Arrose moins en hiver et évite un pot constamment détrempé."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/codiaeum-variegatum/",
  },
  {
    id: "cordyline", name: {"en": "Ti plant", "fr": "Cordyline"},
    genderFr: "f",
    botanical: "Cordyline fruticosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the mix dry a little between waterings. Bright indirect light helps keep its leaf colours.", "fr": "Laisse le terreau sécher un peu entre deux arrosages. Une lumière vive indirecte aide à conserver la couleur des feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/cordyline-fruticosa/",
  },
  {
    id: "pachira", name: {"en": "Money tree", "fr": "Pachira"},
    genderFr: "m", aliases: ["Pachira", "Guiana chestnut"],
    botanical: "Pachira aquatica", water: "moist", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the mix moist and well drained. Standing water can rot the roots; direct sun can scorch the leaves.", "fr": "Garde le terreau humide et bien drainé. L’eau stagnante peut faire pourrir les racines ; le soleil direct peut brûler les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/pachira-aquatica/",
  },
  {
    id: "yucca", name: {"en": "Spineless yucca", "fr": "Yucca"},
    genderFr: "m", aliases: ["Yucca elephantipes", "Yucca guatemalensis"],
    botanical: "Yucca gigantea", water: "moist", light: {"ideal": ["sun"], "tolerated": ["partial"], "avoid": ["low"]},
    note: {"en": "Use a very well-drained mix. It tolerates drought, but too much water can rot its roots.", "fr": "Utilise un terreau très drainant. Il tolère la sécheresse, mais l’excès d’eau peut faire pourrir ses racines."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/yucca-gigantea/",
    waterTolerated: ["surface", "dry"],
  },
  {
    id: "araucaria", name: {"en": "Norfolk Island pine", "fr": "Pin de Norfolk"},
    genderFr: "m",
    botanical: "Araucaria heterophylla", water: "surface", light: {"ideal": ["sun"], "tolerated": ["partial", "indirect"], "avoid": ["low"]},
    note: {"en": "Water regularly during growth without soaking the soil; reduce watering in winter. Lasting low light can cause branch loss.", "fr": "Arrose régulièrement en période de croissance sans détremper le terreau ; arrose moins en hiver. Un manque de lumière durable peut faire tomber les branches."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/araucaria-heterophylla/",
  },
  {
    id: "tradescantia", name: {"en": "Inch plant", "fr": "Misère"},
    genderFr: "f",
    botanical: "Tradescantia zebrina", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial", "sun"], "avoid": ["low"]},
    note: {"en": "Let the mix dry between waterings and water less in winter. Harsh sun can wash out the leaf colours.", "fr": "Laisse sécher le terreau entre deux arrosages et arrose moins en hiver. Un soleil trop intense peut ternir la couleur des feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/tradescantia-zebrina/",
  },
  {
    id: "asparagus", name: {"en": "Asparagus fern", "fr": "Asparagus"},
    genderFr: "m",
    botanical: "Asparagus setaceus", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the mix moist and well drained. Too little water or light can turn the fine foliage yellow; avoid direct sun.", "fr": "Garde le terreau humide et bien drainé. Un manque d’eau ou de lumière peut jaunir le feuillage fin ; évite le soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/asparagus-setaceus/",
  },
  {
    id: "plerandra", name: {"en": "False aralia", "fr": "Aralia élégant"},
    genderFr: "m", aliases: ["Dizygotheca elegantissima", "Schefflera elegantissima"],
    botanical: "Plerandra elegantissima", water: "moist", light: {"ideal": ["partial", "sun"], "tolerated": ["indirect"], "avoid": ["low"]},
    note: {"en": "Keep the mix moist and provide high humidity. It is grown indoors for its finely divided foliage.", "fr": "Garde le terreau humide et offre une bonne humidité ambiante. Cette plante d’intérieur se distingue par son feuillage finement découpé."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/plerandra-elegantissima/",
  },
  {
    id: "polyscias", name: {"en": "Ming aralia", "fr": "Aralia Ming"},
    genderFr: "m",
    botanical: "Polyscias fruticosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the upper soil dry before watering. Avoid both an overly wet and an overly dry pot.", "fr": "Laisse sécher la partie supérieure du terreau avant d’arroser. Évite un pot trop humide comme trop sec."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/polyscias-fruticosa/",
  },
  {
    id: "asplenium", name: {"en": "Bird’s nest fern", "fr": "Fougère nid-d’oiseau"},
    genderFr: "m",
    botanical: "Asplenium nidus", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Do not let the mix dry out. Too much sun can yellow the fronds or stop growth.", "fr": "Ne laisse pas sécher le terreau. Trop de soleil peut jaunir les frondes ou freiner la croissance."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/asplenium-nidus/",
  },
  {
    id: "adiantum", name: {"en": "Maidenhair fern", "fr": "Capillaire"},
    genderFr: "f",
    botanical: "Adiantum raddianum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["low", "sun"]},
    note: {"en": "Keep the roots moist and provide humid air. Deep shade and full sun both weaken this fern.", "fr": "Garde les racines humides et offre une bonne humidité ambiante. Une ombre trop dense et le plein soleil affaiblissent cette fougère."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/adiantum-raddianum/",
  },
  {
    id: "davallia", name: {"en": "Rabbit’s foot fern", "fr": "Fougère patte-de-lapin"},
    genderFr: "f",
    botanical: "Davallia fejeensis", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Keep the mix moist but let its surface dry between waterings. Give it good indirect light.", "fr": "Garde le terreau humide, mais laisse sécher la surface entre deux arrosages. Offre-lui une bonne lumière indirecte."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/davallia-fejeensis/",
  },
  {
    id: "platycerium", name: {"en": "Staghorn fern", "fr": "Corne de cerf"},
    genderFr: "f",
    botanical: "Platycerium bifurcatum", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Let the roots dry slightly between waterings, never completely. Potted plants can be watered from below.", "fr": "Laisse les racines sécher légèrement entre deux arrosages, jamais complètement. En pot, tu peux l’arroser par le bas."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/platycerium-bifurcatum/",
    waterAvoid: ["dry"],
  },
  {
    id: "chamaedorea", name: {"en": "Parlor palm", "fr": "Palmier de salon"},
    genderFr: "m",
    botanical: "Chamaedorea elegans", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Let the mix dry slightly between waterings. It tolerates low light; protect it from cold drafts.", "fr": "Laisse le terreau sécher légèrement entre deux arrosages. Il tolère une faible lumière ; protège-le des courants d’air froid."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chamaedorea-elegans/",
    waterTolerated: ["moist", "dry"],
  },
  {
    id: "kentia", name: {"en": "Kentia palm", "fr": "Kentia"},
    genderFr: "m",
    botanical: "Howea forsteriana", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the mix moist and well drained rather than letting it dry out. Avoid direct sun.", "fr": "Garde le terreau humide et bien drainé plutôt que de le laisser sécher. Évite le soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/howea-forsteriana/",
  },
  {
    id: "areca", name: {"en": "Areca palm", "fr": "Aréca"},
    genderFr: "m", aliases: ["Dypsis lutescens", "Areca lutescens", "Golden cane palm", "Butterfly palm"],
    botanical: "Chrysalidocarpus lutescens", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": []},
    note: {"en": "Keep the mix moist, not soggy, during growth. Indoors, bright indirect light and humid air suit it best.", "fr": "Garde le terreau humide, sans le détremper, en période de croissance. À l’intérieur, il préfère une lumière vive indirecte et une bonne humidité ambiante."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chrysalidocarpus-lutescens/",
  },
  {
    id: "rhapis", name: {"en": "Lady palm", "fr": "Rhapis"},
    genderFr: "m",
    botanical: "Rhapis excelsa", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["sun"]},
    note: {"en": "Water regularly in a well-drained mix and less in winter. It tolerates low light indoors.", "fr": "Arrose régulièrement dans un terreau bien drainé et moins en hiver. Il tolère une faible lumière à l’intérieur."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/rhapis-excelsa/",
  },
  {
    id: "beaucarnea", name: {"en": "Ponytail palm", "fr": "Pied d’éléphant"},
    genderFr: "m", aliases: ["Nolina recurvata", "Elephant’s foot"],
    botanical: "Beaucarnea recurvata", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Let the mix dry between waterings and greatly reduce watering in winter. Its swollen trunk stores water.", "fr": "Laisse sécher le terreau entre deux arrosages et arrose beaucoup moins en hiver. Son tronc renflé stocke l’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/beaucarnea-recurvata/",
  },
  {
    id: "haworthia", name: {"en": "Zebra haworthia", "fr": "Haworthia"},
    genderFr: "m", aliases: ["Haworthia attenuata", "Zebra plant"],
    botanical: "Haworthiopsis attenuata", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    note: {"en": "Let the mix dry between waterings. Direct sun can scorch the leaves; avoid overwatering.", "fr": "Laisse sécher le terreau entre deux arrosages. Le soleil direct peut brûler les feuilles ; évite l’excès d’eau."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/haworthiopsis-attenuata/",
  },
  {
    id: "gasteria", name: {"en": "Gasteria", "fr": "Gastéria"},
    genderFr: "m",
    botanical: "Gasteria gracilis", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Let the mix dry between waterings and use a pot with drainage holes. Protect it from hot afternoon sun.", "fr": "Laisse sécher le terreau entre deux arrosages et utilise un pot percé. Protège-la du soleil brûlant de l’après-midi."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/gasteria-gracilis/",
  },
  {
    id: "sedum", name: {"en": "Burro’s tail", "fr": "Queue d’âne"},
    genderFr: "f", aliases: ["Donkey’s tail"],
    botanical: "Sedum morganianum", water: "dry", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Let the mix dry between waterings and water less in winter. It needs a bright spot with at least some direct sun.", "fr": "Laisse sécher le terreau entre deux arrosages et arrose moins en hiver. Il a besoin d’un emplacement lumineux avec un peu de soleil direct."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/sedum-morganianum/",
  },
  {
    id: "curio", name: {"en": "String of pearls", "fr": "Collier de perles"},
    genderFr: "m", aliases: ["Senecio rowleyanus", "Séneçon de Rowley", "String of beads"],
    botanical: "Curio rowleyanus", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Avoid both constant wetness and complete drying. Direct sun can scorch the leaves.", "fr": "Évite un terreau constamment humide comme un séchage complet. Le soleil direct peut brûler les feuilles."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/curio-rowleyanus/",
    waterAvoid: ["dry"],
  },
  {
    id: "ceropegia", name: {"en": "String of hearts", "fr": "Chaîne des cœurs"},
    genderFr: "f", aliases: ["Chaîne des coeurs", "Rosary vine"],
    botanical: "Ceropegia woodii", water: "dry", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Let the mix dry completely between waterings. Water even less during winter dormancy.", "fr": "Laisse sécher le terreau complètement entre deux arrosages. Arrose encore moins pendant le repos hivernal."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ceropegia-woodii/",
  },
  {
    id: "aeschynanthus", name: {"en": "Lipstick plant", "fr": "Aeschynanthe"},
    genderFr: "m",
    botanical: "Aeschynanthus radicans", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Water regularly but let excess water drain away. It likes humid air with good circulation, not full sun.", "fr": "Arrose régulièrement, mais laisse l’excès d’eau s’écouler. Elle apprécie une bonne humidité ambiante avec de l’air qui circule, pas le plein soleil."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aeschynanthus-radicans/",
  },
  {
    id: "nematanthus", name: {"en": "Goldfish plant", "fr": "Plante poisson rouge"},
    genderFr: "f",
    botanical: "Nematanthus gregarius", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Use a moist, well-drained mix and bright filtered light. Avoid prolonged full sun.", "fr": "Utilise un terreau humide, bien drainé et une lumière vive filtrée. Évite le plein soleil prolongé."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/nematanthus-gregarius/",
  },
  {
    id: "stephanotis", name: {"en": "Madagascar jasmine", "fr": "Stéphanotis"},
    genderFr: "m",
    botanical: "Stephanotis floribunda", water: "moist", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Water well during summer growth and much less during a cool rest. Increase sun exposure gradually to avoid burns.", "fr": "Arrose bien pendant la croissance estivale et beaucoup moins pendant un repos au frais. Augmente progressivement l’exposition au soleil pour éviter les brûlures."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/stephanotis-floribunda/",
  },
  {
    id: "clivia", name: {"en": "Clivia", "fr": "Clivia"},
    genderFr: "m",
    botanical: "Clivia miniata", water: "surface", light: {"ideal": ["partial"], "tolerated": ["indirect", "low"], "avoid": ["sun"]},
    note: {"en": "Morning sun suits it indoors. Avoid overwatering and give it a cool rest if you want it to flower.", "fr": "Le soleil du matin lui convient à l’intérieur. Évite l’excès d’eau et offre-lui un repos au frais pour favoriser la floraison."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/clivia-miniata/",
  },
  {
    id: "gloxinia", name: {"en": "Gloxinia", "fr": "Gloxinia"},
    genderFr: "m", aliases: ["Gloxinia speciosa"],
    botanical: "Sinningia speciosa", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    note: {"en": "Keep the mix moist while it grows, without wetting the crown. Reduce watering when it enters dormancy after flowering.", "fr": "Garde le terreau humide pendant la croissance, sans mouiller le cœur. Réduis les arrosages quand elle entre en repos après la floraison."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/sinningia-speciosa/",
  },
  {
    id: "schlumbergera", name: {"en": "Christmas cactus", "fr": "Cactus de Noël"},
    genderFr: "m", aliases: ["Zygocactus", "Christmas cactus"],
    botanical: "Schlumbergera × buckleyi", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Keep the mix lightly moist during growth, not soggy. Reduce watering after flowering; full sun can bleach the stems.", "fr": "Garde le terreau légèrement humide pendant la croissance, sans le détremper. Arrose moins après la floraison ; le plein soleil peut décolorer les tiges."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/schlumbergera-x-buckleyi/",
  },
  {
    id: "epiphyllum", name: {"en": "Queen of the night", "fr": "Épiphyllum"},
    genderFr: "m", aliases: ["Dutchman’s pipe cactus", "Reine de la nuit"],
    botanical: "Epiphyllum oxypetalum", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Let the surface dry between waterings and water less in winter. Protect it from harsh afternoon sun.", "fr": "Laisse sécher la surface entre deux arrosages et arrose moins en hiver. Protège-le du soleil intense de l’après-midi."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/epiphyllum-oxypetalum/",
  },
  {
    id: "rhipsalis", name: {"en": "Mistletoe cactus", "fr": "Rhipsalis"},
    genderFr: "m",
    botanical: "Rhipsalis baccifera", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    note: {"en": "Water when the mix feels dry, without leaving it waterlogged. Reduce watering during winter rest.", "fr": "Arrose quand le terreau est sec au toucher, sans le laisser détrempé. Réduis les arrosages pendant le repos hivernal."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/rhipsalis-baccifera/",
  },
  {
    id: "hippeastrum", name: {"en": "Amaryllis", "fr": "Amaryllis"},
    genderFr: "m", aliases: ["Amaryllis"],
    botanical: "Hippeastrum", water: "moist", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    note: {"en": "Keep the mix moist during active growth. Reduce watering after flowering when the bulb goes into its rest period.", "fr": "Garde le terreau humide pendant la croissance. Réduis les arrosages après la floraison, quand le bulbe entre en repos."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/hippeastrum/",
  },
  {
    id: "aphelandra", name: {"en": "Zebra plant", "fr": "Aphélandra"},
    genderFr: "m", aliases: ["Plante zèbre"],
    botanical: "Aphelandra squarrosa", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    note: {"en": "Do not let the mix dry completely or leave the roots standing in water. It needs bright indirect light and humid air.", "fr": "Ne laisse pas le terreau sécher complètement ni les racines baigner dans l’eau. Elle a besoin d’une lumière vive indirecte et d’une bonne humidité ambiante."},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aphelandra-squarrosa/",
  },
];
