// Houseplant care profiles: sources and scope in SOURCES.md.
const plants = [
  {
    id: "aloe", name: {"en": "Aloe vera", "fr": "Aloe vera"},
    genderFr: "m",
    botanical: "Aloe vera", water: "dry", light: {"ideal": ["sun", "partial"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Let the soil dry completely before watering again. Use a free-draining succulent soil mix.", "fr": "Laisse sécher complètement la terre avant d’arroser à nouveau. Utilise une terre pour succulentes très drainante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aloe-vera/",
  },
  {
    id: "spider", name: {"en": "Spider plant", "fr": "Plante araignée"},
    genderFr: "f", aliases: ["Chlorophytum", "Spider ivy", "Ribbon plant"],
    botanical: "Chlorophytum comosum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chlorophytum-comosum/",
  },
  {
    id: "peace", name: {"en": "Peace lily", "fr": "Fleur de lune"},
    genderFr: "f", aliases: ["Peace plant", "Lys de la paix", "Spathiphyllum"],
    botanical: "Spathiphyllum", water: "moist", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Protect it from cold drafts.", "fr": "Protège-la des courants d’air froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/spathiphyllum/",
  },
  {
    id: "snake", name: {"en": "Snake plant", "fr": "Langue de belle-mère"},
    genderFr: "f", aliases: ["Sansevieria", "Sansevieria trifasciata", "Mother-in-law’s tongue", "Langue de belle mère"],
    botanical: "Dracaena trifasciata", water: "dry", light: {"ideal": ["partial"], "tolerated": ["indirect", "low"], "avoid": []},
    care: {"light": {"en": "Choose a spot with some direct sun.", "fr": "Choisis un emplacement avec un peu de soleil direct."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/",
  },
  {
    id: "pothos", name: {"en": "Pothos", "fr": "Pothos"},
    genderFr: "m", aliases: ["Scindapsus aureus", "Golden pothos", "Devil’s ivy", "Lierre du diable"],
    botanical: "Epipremnum aureum", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["sun"]},
    care: {"light": {"en": "Choose bright indirect light. Low light may reduce the markings on the leaves.", "fr": "Choisis une lumière vive indirecte. Une faible lumière peut atténuer les panachures des feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/epipremnum-aureum/",
  },
  {
    id: "fiddle", name: {"en": "Fiddle-leaf fig", "fr": "Figuier lyre"},
    genderFr: "m",
    botanical: "Ficus lyrata", water: "moist", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    care: {"light": {"en": "Choose bright indirect light or some gentle sun; protect it from afternoon sun.", "fr": "Choisis une lumière vive indirecte ou un peu de soleil doux ; protège-le du soleil de l’après-midi."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-lyrata/",
  },
  {
    id: "rubber", name: {"en": "Rubber plant", "fr": "Caoutchouc"},
    genderFr: "m",
    botanical: "Ficus elastica", water: "dry", light: {"ideal": ["indirect", "low"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry before watering again. Water less in winter.", "fr": "Laisse sécher la terre avant d’arroser à nouveau. Arrose moins en hiver."}, "light": {"en": "Choose indirect light or a shaded spot; protect it from afternoon sun.", "fr": "Choisis une lumière indirecte ou un emplacement à l’ombre ; protège-le du soleil de l’après-midi."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-elastica/",
  },
  {
    id: "dracaena", name: {"en": "Corn plant", "fr": "Dragonnier parfumé"},
    genderFr: "m",
    botanical: "Dracaena fragrans", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-fragrans/",
  },
  {
    id: "zz", name: {"en": "ZZ plant", "fr": "Plante ZZ"},
    genderFr: "f", aliases: ["Zamioculcas", "Zanzibar gem"],
    botanical: "Zamioculcas zamiifolia", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Let the soil dry completely before watering again.", "fr": "Laisse sécher complètement la terre avant d’arroser à nouveau."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/zamioculcas-zamiifolia/",
  },
  {
    id: "fern", name: {"en": "Boston fern", "fr": "Fougère de Boston"},
    genderFr: "f", aliases: ["Fougère de Boston", "Sword fern"],
    botanical: "Nephrolepis exaltata", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}, "extra": {"en": "Provide humid air around the plant.", "fr": "Offre une bonne humidité ambiante à la plante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/nephrolepis-exaltata/",
    waterAvoid: ["dry"],
  },
  {
    id: "jade", name: {"en": "Jade plant", "fr": "Arbre de jade"},
    genderFr: "m", aliases: ["Crassula", "Money plant"],
    botanical: "Crassula ovata", water: "dry", light: {"ideal": ["partial"], "tolerated": ["indirect"], "avoid": ["low", "sun"]},
    care: {"water": {"en": "Let the soil dry before watering again. Water less from autumn to late winter.", "fr": "Laisse sécher la terre avant d’arroser à nouveau. Arrose moins de l’automne à la fin de l’hiver."}, "light": {"en": "Choose a sunny spot with protection from afternoon sun.", "fr": "Choisis un emplacement ensoleillé, protégé du soleil de l’après-midi."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/crassula-ovata/",
  },
  {
    id: "violet", name: {"en": "African violet", "fr": "Violette africaine"},
    genderFr: "f", aliases: ["Saintpaulia", "Saintpaulia ionantha"],
    botanical: "Streptocarpus ionanthus", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water from below to keep the leaves dry.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose par le bas pour ne pas mouiller les feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/streptocarpus-ionanthus/",
  },
  {
    id: "orchid", name: {"en": "Orchid", "fr": "Orchidée"},
    genderFr: "f", aliases: ["Moth orchid", "Orchidée papillon"],
    botanical: "Phalaenopsis", water: "surface", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Use an orchid mix made with bark and let it dry partly before watering again.", "fr": "Utilise un mélange d’écorces pour orchidées et laisse-le sécher partiellement avant d’arroser à nouveau."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/phalaenopsis/",
  },
  {
    id: "calathea", name: {"en": "Calathea", "fr": "Calathéa"},
    genderFr: "m", aliases: ["Calathea", "Goeppertia"],
    botanical: "Goeppertia", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Avoid cold drafts and sudden temperature changes.", "fr": "Évite les courants d’air froid et les changements brusques de température."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/goeppertia/",
  },
  {
    id: "philodendron", name: {"en": "Heartleaf philodendron", "fr": "Philodendron"},
    genderFr: "m", aliases: ["Philodendron scandens", "Philodendron cordatum", "Sweetheart plant"],
    botanical: "Philodendron hederaceum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/philodendron-hederaceum/",
  },
  {
    id: "monstera", name: {"en": "Monstera", "fr": "Monstera"},
    genderFr: "f", aliases: ["Swiss cheese plant", "Split-leaf philodendron", "Faux philodendron"],
    botanical: "Monstera deliciosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/monstera-deliciosa/",
  },
  {
    id: "bromeliad", name: {"en": "Guzmania", "fr": "Guzmania"},
    genderFr: "m",
    botanical: "Guzmania lingulata", water: "tank", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep water in the central cup, especially in summer, and water the roots sparingly in an orchid or bromeliad mix.", "fr": "Garde de l’eau dans la coupe centrale, surtout en été, et arrose peu les racines dans un mélange pour orchidées ou broméliacées."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/guzmania-lingulata/",
  },
  {
    id: "cactus", name: {"en": "Cactus", "fr": "Cactus"},
    genderFr: "m", aliases: ["Cactus désertique", "Desert cactus", "Pincushion cactus"],
    botanical: "Mammillaria", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Let the soil dry completely before watering again. Stop watering during winter dormancy.", "fr": "Laisse sécher complètement la terre avant d’arroser à nouveau. Suspends les arrosages pendant le repos hivernal."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/mammillaria/",
  },
  {
    id: "echeveria", name: {"en": "Echeveria", "fr": "Échévéria"},
    genderFr: "f",
    botanical: "Echeveria", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/echeveria/",
  },
  {
    id: "hoya", name: {"en": "Wax plant", "fr": "Fleur de porcelaine"},
    genderFr: "f", aliases: ["Hoya", "Wax flower"],
    botanical: "Hoya carnosa", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry between waterings, but avoid leaving it bone dry for long: leaves may fall.", "fr": "Laisse sécher la terre entre deux arrosages, sans prolonger une sécheresse excessive : les feuilles peuvent tomber."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/hoya-carnosa/",
  },
  {
    id: "kalanchoe", name: {"en": "Kalanchoe", "fr": "Kalanchoé"},
    genderFr: "m",
    botanical: "Kalanchoe blossfeldiana", water: "dry", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry, then water thoroughly.", "fr": "Laisse sécher la terre, puis arrose abondamment."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/kalanchoe-blossfeldiana/",
  },
  {
    id: "pilea", name: {"en": "Chinese money plant", "fr": "Pilea"},
    genderFr: "m", aliases: ["Plante à monnaie chinoise", "Pancake plant", "Missionary plant"],
    botanical: "Pilea peperomioides", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/pilea-peperomioides/",
  },
  {
    id: "peperomia", name: {"en": "Peperomia", "fr": "Pépéromia"},
    genderFr: "m",
    botanical: "Peperomia obtusifolia", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Let the surface dry before watering again, without letting the whole pot become bone dry.", "fr": "Laisse sécher la surface avant d’arroser à nouveau, sans laisser toute la terre se dessécher."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/peperomia-obtusifolia/",
  },
  {
    id: "schefflera", name: {"en": "Dwarf umbrella tree", "fr": "Arbre ombrelle"},
    genderFr: "m", aliases: ["Schefflera arboricola", "Dwarf schefflera", "Parasol"],
    botanical: "Heptapleurum arboricola", water: "dry", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry, then water thoroughly.", "fr": "Laisse sécher la terre, puis arrose abondamment."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/heptapleurum-arboricola/",
  },
  {
    id: "ficus", name: {"en": "Weeping fig", "fr": "Figuier pleureur"},
    genderFr: "m", aliases: ["Ficus benjamina"],
    botanical: "Ficus benjamina", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial", "low"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the surface dry, but water before the whole pot dries completely.", "fr": "Laisse sécher la surface, mais arrose avant que toute la terre ne sèche complètement."}, "light": {"en": "Choose bright indirect light and keep the spot stable: moving to different light may cause leaf drop.", "fr": "Choisis une lumière vive indirecte et un emplacement stable : changer d’exposition peut faire tomber les feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-benjamina/",
    waterAvoid: ["dry"],
  },
  {
    id: "anthurium", name: {"en": "Anthurium", "fr": "Anthurium"},
    genderFr: "m",
    botanical: "Anthurium andraeanum", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Protect it from cold drafts.", "fr": "Protège-la des courants d’air froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/anthurium-andraeanum/",
  },
  {
    id: "rex", name: {"en": "Rex begonia", "fr": "Bégonia rex"},
    genderFr: "m", aliases: ["Begonia rex"],
    botanical: "Begonia Rex Cultorum Group", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Avoid misting the leaves.", "fr": "Évite de brumiser les feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/begonia-rex-types/",
  },
  {
    id: "maranta", name: {"en": "Prayer plant", "fr": "Maranta"},
    genderFr: "m",
    botanical: "Maranta leuconeura", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/maranta-leuconeura/",
  },
  {
    id: "marginata", name: {"en": "Dragon tree", "fr": "Dragonnier de Madagascar"},
    genderFr: "m", aliases: ["Dracaena reflexa var. angustifolia"],
    botanical: "Dracaena marginata", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry a little between waterings, without prolonged drying.", "fr": "Laisse sécher un peu la terre entre deux arrosages, sans sécheresse prolongée."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dracaena-reflexa-var-angustifolia/",
  },
  {
    id: "cyclamen", name: {"en": "Florist’s cyclamen", "fr": "Cyclamen des fleuristes"},
    genderFr: "m",
    botanical: "Cyclamen persicum", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Water when the soil surface feels dry, without wetting the crown. Water less during summer dormancy.", "fr": "Arrose quand la surface de la terre est sèche, sans mouiller le cœur. Arrose moins pendant le repos estival."}, "extra": {"en": "Keep it in a cool room.", "fr": "Garde la plante dans une pièce fraîche."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/cyclamen-persicum/",
  },
  {
    id: "aglaonema", name: {"en": "Chinese evergreen", "fr": "Aglaonema"},
    genderFr: "m",
    botanical: "Aglaonema", water: "moist", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}, "extra": {"en": "Protect it from cold drafts.", "fr": "Protège-la des courants d’air froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aglaonema/",
  },
  {
    id: "alocasia", name: {"en": "Alocasia", "fr": "Alocasia"},
    genderFr: "f", aliases: ["Alocasia amazonica", "Alocasia × amazonica", "Alocasia mortfontanensis", "African mask plant"],
    botanical: "Alocasia × mortfontanensis", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less when growth slows.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins quand la croissance ralentit."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/alocasia-x-mortfontanensis/",
  },
  {
    id: "aspidistra", name: {"en": "Cast iron plant", "fr": "Aspidistra"},
    genderFr: "f", aliases: ["Plante de fer"],
    botanical: "Aspidistra elatior", water: "surface", light: {"ideal": ["indirect", "low"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water less in winter.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aspidistra-elatior/",
  },
  {
    id: "dieffenbachia", name: {"en": "Dieffenbachia", "fr": "Dieffenbachia"},
    genderFr: "m",
    botanical: "Dieffenbachia seguine", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Protect it from cold drafts.", "fr": "Protège-la des courants d’air froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/dieffenbachia-seguine/",
  },
  {
    id: "syngonium", name: {"en": "Arrowhead plant", "fr": "Syngonium"},
    genderFr: "m", aliases: ["Nephthytis"],
    botanical: "Syngonium podophyllum", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/syngonium-podophyllum/",
  },
  {
    id: "fittonia", name: {"en": "Nerve plant", "fr": "Fittonia"},
    genderFr: "m",
    botanical: "Fittonia albivenis", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist: this plant wilts quickly when it dries out.", "fr": "Garde la terre légèrement humide : cette plante s’affaisse vite quand elle sèche."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/fittonia-albivenis/",
  },
  {
    id: "croton", name: {"en": "Croton", "fr": "Croton"},
    genderFr: "m", aliases: ["Codiaeum"],
    botanical: "Codiaeum variegatum", water: "surface", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water less in winter.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose moins en hiver."}, "light": {"en": "Choose a bright spot with some direct sun or full sun to keep the leaves colourful.", "fr": "Choisis un emplacement lumineux avec quelques heures de soleil ou du plein soleil pour conserver la couleur des feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/codiaeum-variegatum/",
  },
  {
    id: "cordyline", name: {"en": "Ti plant", "fr": "Cordyline"},
    genderFr: "f",
    botanical: "Cordyline fruticosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"light": {"en": "Choose bright indirect light to help preserve the leaf colours.", "fr": "Choisis une lumière vive indirecte pour préserver la couleur des feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/cordyline-fruticosa/",
  },
  {
    id: "pachira", name: {"en": "Money tree", "fr": "Pachira"},
    genderFr: "m", aliases: ["Pachira", "Guiana chestnut"],
    botanical: "Pachira aquatica", water: "moist", light: {"ideal": ["indirect", "partial"], "tolerated": [], "avoid": ["sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/pachira-aquatica/",
  },
  {
    id: "yucca", name: {"en": "Spineless yucca", "fr": "Yucca"},
    genderFr: "m", aliases: ["Yucca elephantipes", "Yucca guatemalensis"],
    botanical: "Yucca gigantea", water: "moist", light: {"ideal": ["sun"], "tolerated": ["partial"], "avoid": ["low"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth in a very free-draining soil mix.", "fr": "Garde la terre légèrement humide pendant la croissance, dans un mélange très drainant."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/yucca-gigantea/",
    waterTolerated: ["surface", "dry"],
  },
  {
    id: "araucaria", name: {"en": "Norfolk Island pine", "fr": "Pin de Norfolk"},
    genderFr: "m",
    botanical: "Araucaria heterophylla", water: "surface", light: {"ideal": ["sun"], "tolerated": ["partial", "indirect"], "avoid": ["low"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water less in winter.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose moins en hiver."}, "light": {"en": "Choose a sunny spot. Prolonged low light may cause branch loss.", "fr": "Choisis un emplacement ensoleillé. Un manque de lumière durable peut faire tomber les branches."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/araucaria-heterophylla/",
  },
  {
    id: "tradescantia", name: {"en": "Inch plant", "fr": "Misère"},
    genderFr: "f",
    botanical: "Tradescantia zebrina", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial", "sun"], "avoid": ["low"]},
    care: {"water": {"en": "Let the soil dry before watering again. Water less in winter.", "fr": "Laisse sécher la terre avant d’arroser à nouveau. Arrose moins en hiver."}, "light": {"en": "Choose bright indirect light. Harsh sun may fade the leaf colours.", "fr": "Choisis une lumière vive indirecte. Un soleil intense peut ternir la couleur des feuilles."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/tradescantia-zebrina/",
  },
  {
    id: "asparagus", name: {"en": "Asparagus fern", "fr": "Asparagus"},
    genderFr: "m",
    botanical: "Asparagus setaceus", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/asparagus-setaceus/",
  },
  {
    id: "plerandra", name: {"en": "False aralia", "fr": "Aralia élégant"},
    genderFr: "m", aliases: ["Dizygotheca elegantissima", "Schefflera elegantissima"],
    botanical: "Plerandra elegantissima", water: "moist", light: {"ideal": ["partial", "sun"], "tolerated": ["indirect"], "avoid": ["low"]},
    care: {"extra": {"en": "Provide humid air around the plant.", "fr": "Offre une bonne humidité ambiante à la plante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/plerandra-elegantissima/",
  },
  {
    id: "polyscias", name: {"en": "Ming aralia", "fr": "Aralia Ming"},
    genderFr: "m",
    botanical: "Polyscias fruticosa", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the upper soil dry before watering again, without letting the whole pot dry completely.", "fr": "Laisse sécher la partie supérieure de la terre avant d’arroser à nouveau, sans laisser tout le pot se dessécher."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/polyscias-fruticosa/",
  },
  {
    id: "asplenium", name: {"en": "Bird’s nest fern", "fr": "Fougère nid-d’oiseau"},
    genderFr: "f",
    botanical: "Asplenium nidus", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"light": {"en": "Choose bright indirect light. Too much sun may yellow the fronds or slow growth.", "fr": "Choisis une lumière vive indirecte. Trop de soleil peut jaunir les feuilles ou freiner la croissance."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/asplenium-nidus/",
  },
  {
    id: "adiantum", name: {"en": "Maidenhair fern", "fr": "Capillaire"},
    genderFr: "f",
    botanical: "Adiantum raddianum", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["low", "sun"]},
    care: {"extra": {"en": "Provide humid air around the plant.", "fr": "Offre une bonne humidité ambiante à la plante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/adiantum-raddianum/",
  },
  {
    id: "davallia", name: {"en": "Rabbit’s foot fern", "fr": "Fougère patte-de-lapin"},
    genderFr: "f",
    botanical: "Davallia fejeensis", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/davallia-fejeensis/",
  },
  {
    id: "platycerium", name: {"en": "Staghorn fern", "fr": "Corne de cerf"},
    genderFr: "f",
    botanical: "Platycerium bifurcatum", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the roots dry slightly, never completely. In a pot, water from below.", "fr": "Laisse les racines sécher légèrement, jamais complètement. En pot, arrose par le bas."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/platycerium-bifurcatum/",
    waterAvoid: ["dry"],
  },
  {
    id: "chamaedorea", name: {"en": "Parlor palm", "fr": "Palmier de salon"},
    genderFr: "m",
    botanical: "Chamaedorea elegans", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Protect it from cold drafts.", "fr": "Protège-la des courants d’air froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chamaedorea-elegans/",
    waterTolerated: ["moist", "dry"],
  },
  {
    id: "kentia", name: {"en": "Kentia palm", "fr": "Kentia"},
    genderFr: "m",
    botanical: "Howea forsteriana", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/howea-forsteriana/",
  },
  {
    id: "areca", name: {"en": "Areca palm", "fr": "Aréca"},
    genderFr: "m", aliases: ["Dypsis lutescens", "Areca lutescens", "Golden cane palm", "Butterfly palm"],
    botanical: "Chrysalidocarpus lutescens", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": []},
    care: {"extra": {"en": "Provide humid air around the plant.", "fr": "Offre une bonne humidité ambiante à la plante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/chrysalidocarpus-lutescens/",
  },
  {
    id: "rhapis", name: {"en": "Lady palm", "fr": "Rhapis"},
    genderFr: "m",
    botanical: "Rhapis excelsa", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less in winter.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/rhapis-excelsa/",
  },
  {
    id: "beaucarnea", name: {"en": "Ponytail palm", "fr": "Pied d’éléphant"},
    genderFr: "m", aliases: ["Nolina recurvata", "Elephant’s foot"],
    botanical: "Beaucarnea recurvata", water: "dry", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Let the soil dry completely before watering again. Water much less during winter rest.", "fr": "Laisse sécher complètement la terre avant d’arroser à nouveau. Arrose beaucoup moins pendant le repos hivernal."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/beaucarnea-recurvata/",
  },
  {
    id: "haworthia", name: {"en": "Zebra haworthia", "fr": "Haworthia"},
    genderFr: "m", aliases: ["Haworthia attenuata", "Zebra plant"],
    botanical: "Haworthiopsis attenuata", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["low"], "avoid": ["partial", "sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/haworthiopsis-attenuata/",
  },
  {
    id: "gasteria", name: {"en": "Gasteria", "fr": "Gastéria"},
    genderFr: "m",
    botanical: "Gasteria gracilis", water: "dry", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"light": {"en": "Choose bright indirect light; protect it from hot afternoon sun.", "fr": "Choisis une lumière vive indirecte ; protège-le du soleil brûlant de l’après-midi."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/gasteria-gracilis/",
  },
  {
    id: "sedum", name: {"en": "Burro’s tail", "fr": "Queue d’âne"},
    genderFr: "f", aliases: ["Donkey’s tail"],
    botanical: "Sedum morganianum", water: "dry", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Let the soil dry before watering again. Water less in winter.", "fr": "Laisse sécher la terre avant d’arroser à nouveau. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/sedum-morganianum/",
  },
  {
    id: "curio", name: {"en": "String of pearls", "fr": "Collier de perles"},
    genderFr: "m", aliases: ["Senecio rowleyanus", "Séneçon de Rowley", "String of beads"],
    botanical: "Curio rowleyanus", water: "surface", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the surface dry before watering again, but do not let the whole pot dry completely.", "fr": "Laisse sécher la surface avant d’arroser à nouveau, sans laisser toute la terre se dessécher."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/curio-rowleyanus/",
    waterAvoid: ["dry"],
  },
  {
    id: "ceropegia", name: {"en": "String of hearts", "fr": "Chaîne des cœurs"},
    genderFr: "f", aliases: ["Chaîne des coeurs", "Rosary vine"],
    botanical: "Ceropegia woodii", water: "dry", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Let the soil dry completely before watering again. Water much less during winter rest.", "fr": "Laisse sécher complètement la terre avant d’arroser à nouveau. Arrose beaucoup moins pendant le repos hivernal."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ceropegia-woodii/",
  },
  {
    id: "aeschynanthus", name: {"en": "Lipstick plant", "fr": "Aeschynanthe"},
    genderFr: "m",
    botanical: "Aeschynanthus radicans", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"extra": {"en": "Provide humid air with good air circulation.", "fr": "Offre une bonne humidité ambiante avec de l’air qui circule."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aeschynanthus-radicans/",
  },
  {
    id: "nematanthus", name: {"en": "Goldfish plant", "fr": "Plante poisson rouge"},
    genderFr: "f",
    botanical: "Nematanthus gregarius", water: "moist", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/nematanthus-gregarius/",
  },
  {
    id: "stephanotis", name: {"en": "Madagascar jasmine", "fr": "Stéphanotis"},
    genderFr: "m",
    botanical: "Stephanotis floribunda", water: "moist", light: {"ideal": ["sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Keep the soil moist during summer growth. Water much less during a cool rest.", "fr": "Garde la terre humide pendant la croissance estivale. Arrose beaucoup moins pendant un repos au frais."}, "light": {"en": "Choose a sunny spot, increasing exposure gradually to avoid leaf burns.", "fr": "Choisis un emplacement ensoleillé en augmentant progressivement l’exposition pour éviter les brûlures."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/stephanotis-floribunda/",
  },
  {
    id: "clivia", name: {"en": "Clivia", "fr": "Clivia"},
    genderFr: "m",
    botanical: "Clivia miniata", water: "surface", light: {"ideal": ["partial"], "tolerated": ["indirect", "low"], "avoid": ["sun"]},
    care: {"light": {"en": "Choose a spot with morning sun, protected from strong afternoon sun.", "fr": "Choisis un emplacement avec du soleil le matin, protégé du soleil intense de l’après-midi."}, "extra": {"en": "Give it a cool rest to encourage flowering.", "fr": "Offre-lui un repos au frais pour favoriser la floraison."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/clivia-miniata/",
  },
  {
    id: "gloxinia", name: {"en": "Gloxinia", "fr": "Gloxinia"},
    genderFr: "m", aliases: ["Gloxinia speciosa"],
    botanical: "Sinningia speciosa", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth without wetting the crown. Water less during dormancy after flowering.", "fr": "Garde la terre légèrement humide pendant la croissance sans mouiller le cœur. Arrose moins pendant le repos après la floraison."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/sinningia-speciosa/",
  },
  {
    id: "schlumbergera", name: {"en": "Christmas cactus", "fr": "Cactus de Noël"},
    genderFr: "m", aliases: ["Zygocactus", "Christmas cactus"],
    botanical: "Schlumbergera × buckleyi", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less after flowering.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins après la floraison."}, "light": {"en": "Choose bright indirect light. Full sun may bleach the stems.", "fr": "Choisis une lumière vive indirecte. Le plein soleil peut décolorer les tiges."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/schlumbergera-x-buckleyi/",
  },
  {
    id: "epiphyllum", name: {"en": "Queen of the night", "fr": "Épiphyllum"},
    genderFr: "m", aliases: ["Dutchman’s pipe cactus", "Reine de la nuit"],
    botanical: "Epiphyllum oxypetalum", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water less in winter.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose moins en hiver."}, "light": {"en": "Choose bright indirect light or gentle sun; protect it from harsh afternoon sun.", "fr": "Choisis une lumière vive indirecte ou du soleil doux ; protège-le du soleil intense de l’après-midi."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/epiphyllum-oxypetalum/",
  },
  {
    id: "rhipsalis", name: {"en": "Mistletoe cactus", "fr": "Rhipsalis"},
    genderFr: "m",
    botanical: "Rhipsalis baccifera", water: "surface", light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": ["sun"]},
    care: {"water": {"en": "Let the surface dry before watering again. Water less in winter.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Arrose moins en hiver."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/rhipsalis-baccifera/",
  },
  {
    id: "hippeastrum", name: {"en": "Amaryllis", "fr": "Amaryllis"},
    genderFr: "m", aliases: ["Amaryllis"],
    botanical: "Hippeastrum", water: "moist", light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": ["low"]},
    care: {"water": {"en": "Keep the soil lightly moist during growth. Water less when the bulb enters its rest after flowering.", "fr": "Garde la terre légèrement humide pendant la croissance. Arrose moins quand le bulbe entre en repos après la floraison."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/hippeastrum/",
  },
  {
    id: "aphelandra", name: {"en": "Zebra plant", "fr": "Aphélandra"},
    genderFr: "m", aliases: ["Plante zèbre"],
    botanical: "Aphelandra squarrosa", water: "moist", light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["sun"]},
    care: {"extra": {"en": "Provide humid air around the plant.", "fr": "Offre une bonne humidité ambiante à la plante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/aphelandra-squarrosa/",
  },
  {
    id: "strelitzia",
    name: {"en": "White bird of paradise", "fr": "Oiseau de paradis blanc"},
    genderFr: "m",
    aliases: ["Strelitzia", "Giant bird of paradise", "Oiseau de paradis"],
    botanical: "Strelitzia nicolai",
    water: "surface",
    light: {"ideal": ["indirect"], "tolerated": [], "avoid": []},
    care: {"extra": {"en": "Protect it from cold drafts and sudden temperature changes; it likes humid air.", "fr": "Protège-le des courants d’air froid et des changements brusques de température ; il apprécie une bonne humidité ambiante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/strelitzia-nicolai/",
  },
  {
    id: "maculata",
    name: {"en": "Polka dot begonia", "fr": "Bégonia à pois"},
    genderFr: "m",
    aliases: ["Bégonia maculata", "Begonia à pois", "Spotted begonia"],
    botanical: "Begonia maculata",
    water: "moist",
    light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Provide humid air with good air circulation. Pinch stem tips for a bushier plant.", "fr": "Offre une bonne humidité ambiante avec de l’air qui circule. Pince le bout des tiges pour une plante plus touffue."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/begonia-cane-types/",
  },
  {
    id: "coffee",
    name: {"en": "Coffee plant", "fr": "Caféier"},
    genderFr: "m",
    aliases: ["Arabian coffee", "Caféier arabica"],
    botanical: "Coffea arabica",
    water: "moist",
    light: {"ideal": ["indirect"], "tolerated": ["partial"], "avoid": []},
    care: {"extra": {"en": "Provide humid air and protect it from cold.", "fr": "Offre une bonne humidité ambiante et protège-le du froid."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/coffea-arabica/",
  },
  {
    id: "scindapsus",
    name: {"en": "Satin pothos", "fr": "Pothos argenté"},
    genderFr: "m",
    aliases: ["Silk pothos", "Silver pothos", "Scindapsus argyraeus", "Pothos argyraeus"],
    botanical: "Scindapsus pictus",
    water: "moist",
    light: {"ideal": ["indirect"], "tolerated": [], "avoid": ["partial", "sun"]},
    care: {"extra": {"en": "Keep it away from cold air. Pinch stem tips if you want a compact plant.", "fr": "Protège-le de l’air froid. Pince le bout des tiges pour garder une plante compacte."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/scindapsus-pictus/",
  },
  {
    id: "oxalis",
    name: {"en": "Purple shamrock", "fr": "Oxalis pourpre"},
    genderFr: "m",
    aliases: ["Faux trèfle", "Trèfle pourpre", "False shamrock", "Love plant", "Oxalis regnellii"],
    botanical: "Oxalis triangularis",
    water: "surface",
    light: {"ideal": ["partial", "sun"], "tolerated": [], "avoid": []},
    care: {"water": {"en": "Let the surface dry before watering again. During dormancy, water less and wait for new growth.", "fr": "Laisse sécher la surface avant d’arroser à nouveau. Pendant le repos, arrose moins et attends de nouvelles pousses."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/oxalis-triangularis/",
  },
  {
    id: "ginseng",
    name: {"en": "Ginseng ficus", "fr": "Ficus ginseng"},
    genderFr: "m",
    aliases: ["Ficus bonsai", "Bonsaï ficus", "Pot-bellied ficus"],
    botanical: "Ficus microcarpa 'Ginseng'",
    water: "moist",
    light: {"ideal": ["sun"], "tolerated": [], "avoid": []},
    care: {"extra": {"en": "Keep it warm and provide humid air.", "fr": "Garde-le au chaud et offre une bonne humidité ambiante."}},
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ficus-microcarpa-ginseng/",
  },
];
